# Generated by Django 6.1.2 on 2026-10-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_api_key', models.TextField(blank=True)),
                ('api_key_hint', models.CharField(blank=True, max_length=8)),
                ('api_key_updated_at', models.DateTimeField(blank=True, null=True)),
                ('default_model', models.CharField(blank=True, max_length=200)),
                ('agent_models', models.JSONField(blank=True, default=dict)),
                ('temperature', models.FloatField(default=0.3)),
                ('max_tokens', models.PositiveIntegerField(default=1500)),
                ('max_tool_rounds', models.PositiveSmallIntegerField(default=5)),
                ('max_delegations', models.PositiveSmallIntegerField(default=3)),
                ('request_timeout', models.PositiveSmallIntegerField(default=60)),
                ('research_region', models.CharField(choices=[('za-en', 'South Africa'), ('us-en', 'United States'), ('uk-en', 'United Kingdom'), ('au-en', 'Australia'), ('ca-en', 'Canada'), ('in-en', 'India'), ('de-de', 'Germany'), ('wt-wt', 'Worldwide')], default='za-en', max_length=8)),
                ('currency', models.CharField(choices=[('ZAR', 'South African rand'), ('USD', 'US dollar'), ('EUR', 'Euro'), ('GBP', 'British pound'), ('AUD', 'Australian dollar'), ('CAD', 'Canadian dollar'), ('INR', 'Indian rupee')], default='ZAR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'workspace settings',
                'verbose_name_plural': 'workspace settings',
            },
        ),
    ]
