# Generated by Django 6.1.2 on 2026-10-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(max_length=700, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('seller', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('price_text', models.CharField(blank=True, max_length=64)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='research.conversation')),
            ],
            options={
                'ordering': ['added_at', 'id'],
            },
        ),
    ]
