# Generated by Django 6.1.2 on 2026-10-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('product_search', 'Product search'), ('agent_search', 'Web search agent'), ('agent_scrape', 'Scraper agent')], max_length=32)),
                ('retailer', models.CharField(blank=True, choices=[('takealot', 'Takealot'), ('checkers', 'Checkers'), ('woolworths', 'Woolworths'), ('picknpay', 'Pick n Pay')], help_text='Retailer for scraper-agent runs; blank for multi-retailer or web searches.', max_length=32)),
                ('query', models.TextField()),
                ('retailers', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some retailers failed)'), ('failed', 'Failed')], max_length=16)),
                ('http_status', models.PositiveSmallIntegerField()),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('answer', models.TextField(blank=True)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Agent metadata such as web-search queries, sources, or scraper actions.')),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='history_run_kind_created'), models.Index(fields=['status', '-created_at'], name='history_run_status_created')],
            },
        ),
        migrations.CreateModel(
            name='SearchRunProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('retailer', models.CharField(db_index=True, max_length=32)),
                ('title', models.TextField()),
                ('price', models.CharField(blank=True, max_length=64, null=True)),
                ('url', models.URLField(max_length=2000)),
                ('rating', models.CharField(blank=True, max_length=255, null=True)),
                ('in_stock', models.BooleanField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='history.searchrun')),
            ],
            options={
                'ordering': ['run', 'position'],
                'constraints': [models.UniqueConstraint(fields=('run', 'position'), name='history_product_run_position')],
            },
        ),
    ]
