# Generated by Django 6.1.2 on 2026-10-06 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New research', max_length=200)),
                ('research_context', models.JSONField(blank=True, default=dict, help_text='Products and sources retrieved in this conversation, shared by all agents.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Agent')], max_length=16)),
                ('agent', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('streaming', 'Streaming'), ('cancelled', 'Cancelled'), ('error', 'Error')], default='complete', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Products, sources, comparison, tool activity, delegation, and errors.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='research.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='research_msg_conv_created')],
            },
        ),
    ]
